name: Automated Release

# Controls when the workflow will run
on:
  # Triggers the workflow on updates to the "main" branch which include a version tag
  push:
    branches:
      - 'main'
    tags:        
      - '**'           # Push events to every tag including hierarchical tags like v1.0/beta

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Check-Tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check tag is version tag
        # if: startsWith(github.ref, 'refs/tags/v')
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "The string starts with 'refs/tags/v'"
            # Your code here if the condition is true
            exit 0
          else
            echo "The string does not start with 'refs/tags/v'"
            # Your code here if the condition is false
            exit 1
          fi
  Release:
    environment: release
    runs-on: ubuntu-latest
    needs: [Check-Tag]
    steps:
      - name: Mock release
        run: echo "Release completed"
      # - name: Checkout the main branch
      #   uses: actions/checkout@v4
      # - name: Install Dependencies
      #   run: |
      #     apt-get update
      #     apt-get install -y build-essential g++ libx11-dev libxkbfile-dev libsecret-1-dev libkrb5-dev python-is-python3 quilt
      # - name: Build Tarball
      #   run: sh ./scripts/install.sh -v 
      # - name: Publish Release
      #   uses: softprops/action-gh-release@v2
      #   # if: startsWith(github.ref, 'refs/tags/v')
      #   with:
      #     files: |
      #       helloworld.py
      #       helloworld2.py
